version: 2.1
jobs:
  build:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run:
          name: Test
          command: |
            yarn install
            yarn test

      - run:
          name: Tagging
          command: |
            cat version.txt


  deploy:
    docker:
      - image: node:16-alpine
    steps:
      - run:
          command: |
            yarn install

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
